apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:1e0uwInILDdWlhqPuaQbmVZI7mhTBe5oICLkmoe9kkcH6HUXWyrP4Q==,iv:Ye7kf1xahufjFNhEMzwM3stocb+tJboiL6fn9znOt+M=,tag:EJb7OAJ6xGgNaCVZClRtYQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1twdqg4pwl3ncan7rq2ynlhnjqaggj9cdwdw7cun4rzdj56mtq4nsvk674s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUK0JrRmRJbVl2anEyaGhm
            SFpsNlBValpoc0NtT1pJK0UwS2V0Um1JYlNZCktDMnM2TThJUkpQd1AwU1ZTemVs
            S3pBNW9Tb0FBeVh6RGlzeCtnOEUreGsKLS0tIFN5akYvcUg2Wjd4RWJsV0JFRlMv
            Wjd5elN0R0RQTUJ2T0l6NUV4VXVoR00Kp+Hl+QdUn1aIWJNQtJ5buc2HpWKJpcyD
            9FVBApk0hFOv7b/GSAkqU8hX5b3J0L9FZiPgWcicbxpUbkKZpMCUSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-20T14:37:50Z"
    mac: ENC[AES256_GCM,data:Eo2Q9cQYn/UbusS+Q9SJ9vL/SfYNgc9e9dVVs8D6h/NO85QSdl2O7lDaUEOxZ+vAx1CgPzhMWjJcIdL4gaBiuI5VQEURkS5iqBoCnBCX1Ph9WcJt0JuLg3xVdA8p14nw5X3lKjbdCyjBXsS9x0mo1bfAhGOGGjHhuXO58nzz7Vk=,iv:MfRBYhwcNmY5RnDTAqJ8zAgQONOVg11NN2V+ByEP4KE=,tag:0Ow8N5vNE2vbo89zVSEFWw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
