apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:S+pGGGo8ppdcxohJAu5680nZsSSw5YMxNU0cMTQZ9Nk/x1r+zmhiZA==,iv:tHEq4Ff1LAx/Aki71zDSyQoM9Y4vC7kEqTFXS6HLQ6E=,tag:fcC/0Y50NLZfIbUlXi7Ajg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1twdqg4pwl3ncan7rq2ynlhnjqaggj9cdwdw7cun4rzdj56mtq4nsvk674s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtWDRBdUp3NzRjM0l2WUpY
            WGtLbmE2LzdtS2tqL2ZjV1dRcGllQzNTNGdRClJESEx4WW5aeVBMYkZTSiszTnpU
            WVVLOUVmZEt6TW4zenNDTTNQeVhVZzgKLS0tIEpEekNuVkszdlhxM2t6VDFVdDRy
            b0VRRlhDWEtYSWRKVjFuT0dpVmptbTAK9ezFZLz51e8xrZZyEs+RxhPiGg2i3CF4
            B7HH4Du3F+Yb5jbA4fJFrxRCpKUCUmxWxQBA7bFmb7ZncqF5luKDCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-20T14:37:50Z"
    mac: ENC[AES256_GCM,data:/hCPkbUIOHw6ixYKkr3SiCprnXGhzk2F5pnaS0/v39jE0ulocZGbS+GxPkmfdoHbXvQYxXpIOT9h0w/mOSNJ6TBMmk5lLWvTKz+23KFEIlNoibI6kPPfCFqnyRpoWapPMCSxCNNiWLKiUHslwys8LX6tUyS7FL2qPnPQNCSzxhQ=,iv:BhLhsRk3RO7P6O8OrEldWLWNdeVLE5nucgEJbFSjxv8=,tag:PlqhMyUbvHDnuXvo9SQjiA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
