apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:0PvyK2UBfTH/834BoEWAf/2wqcb80GQ3tlXUsn2UlAzkQwzh4IsS9w==,iv:7sZIjsHpvALQwYPuLMA7XYaDOGWdNYkRogP2k2djRPU=,tag:8TJS6Wz9XSbBvlbtAQZRDQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1twdqg4pwl3ncan7rq2ynlhnjqaggj9cdwdw7cun4rzdj56mtq4nsvk674s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQYkNTajlTVTB1OS8rYkVl
            RER5dGJvOE5lQklUcGcxdU9Ld3RlZjdvZzNVClB0bjd5RGFlYzRmajQ5bXg2K2Fh
            UWhSSlZoZzFRL0F0TWVTcU53cEV2Sk0KLS0tIHRtbm9PVmFHeEEwWDJlZGlMdGx1
            d0kzbXo5dFB1Y1BMcFBGbDhIODhFcU0KtABU64raZVLGofpVdNqyrWNneY5v+3Wq
            kuofFFdhWRfgM0qH0Dw4QUYPmll7kVtyj+IemPh8Q4pCTRa4aVJMsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-24T16:47:18Z"
    mac: ENC[AES256_GCM,data:wE4k1k35UX47Le6oPfKBYjIkwa+CAAHZyIFjynAZTdaSFjKU5tqwRMhoJVOiN//0FOr3m+kPElv8iVSeePykULEPo2UlEn6M+X0i+PzHip9AnYfxETlAmtCLfxm1rRUYX/2tfyssLPxozHCg22I7FeESJosDxF2sFAAIPLA8hro=,iv:J6T4iC50asTLvhv7leVLowyY9Xtg+NU+zRzc+WcLfjM=,tag:hxSxT30EUwFuNgGUdno9Lw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
