apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:sqk6qn6COWyfIeximl0m+enGYPogfuEIUR4iIv0AzpDLmHrKhjT3CH97ax5FnLRLxHFmy1gTf8ZlRpy4,iv:VkKYZ7LJO3hbmHK/cx6QE0ba2kkMNkBOoV1Er0NoxSo=,tag:jES27bRdhlwSrwmhyTnVvA==,type:str]
    username: ENC[AES256_GCM,data:FEXKVMA=,iv:hKnq1wkRxa04mgRrLhyUOLJs/ev+PQiFWFFsT3yuVl4=,tag:rm6Ph8jAy+UWR4Kdcmtqfg==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1twdqg4pwl3ncan7rq2ynlhnjqaggj9cdwdw7cun4rzdj56mtq4nsvk674s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOQ2ZDLzR0b2xZd2JRYWJz
            TzMrUysrelZHSTY2UmQyRDhyVTcwTXRWc2d3Cm5zTE11R250RGZNOEhpQ1NhY0JD
            Z24vaXI0T2JOazJTcHpMNjJiVmszRVkKLS0tIGVIUGxpblpIazhrUDBWdDczUm41
            Ui90ZmZ1RE14Zk56MHY3M2tBclVnSHMK3+TAuw1F5ULVB/LXUW20UQVckU9T/71g
            VSguSnEgJE3LKqZPKbebipXZUIX8P0EWFCnXZP+DsS3gdNOBm/GTAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-24T16:47:30Z"
    mac: ENC[AES256_GCM,data:v8yzGC3moPUW8UGop/XhthmyuYv06TNHGPQ8IlTK/BiI/6jO0M/44ucN7/oXp8DRb/qjVtX+ZroYVGwA/+rRowQVvCD4WAOgfJD9ZBwkzvYskYV0eWpajYfVUbF8/B2FcA/jKRj93+Qzf3OiBwSU/VCWbOIJPEfIrZHLCSN3Wg0=,iv:Qbfb34kddWykyQDL96p/OVvXCxYa0/NQWW32T+llAUc=,tag:ujbLuVAZ1xC2QJzLf7z2Vg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
