apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:RrTT44WQP8g8CF8H9eYC3CGRjT1Zv8Q13T1RIdPIcZRO9J1eIRZvlY2XGbBtICn+LfoA2QeHrolo14U5,iv:GZlYdj0Ujlp9H4aNZyZs8gX0ccr+YIM1GvRswg6TJJ0=,tag:xMsura/husY2ueBqXiq9zQ==,type:str]
    username: ENC[AES256_GCM,data:rHEypA0=,iv:ggQQirOPJRko+U0JzZJ+TqWh0CsNmA25ounUqXd3K+s=,tag:RbQa47RUAVk7j/t5kwiUNw==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1twdqg4pwl3ncan7rq2ynlhnjqaggj9cdwdw7cun4rzdj56mtq4nsvk674s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJL2VJM2lCZWl3TWtKZXlL
            dUZYU3RJQmlWM0N4emlBaldtN0NneXNhSmd3CmZyZ0ZJOS9YaW5lVG93L2dRWlRz
            K0QvTHRjSmQ3Tm5ncWhNcEJuRndvU1UKLS0tIDEvVU8rbWtpQUx1a2hDK1drQVE3
            bUN3T3RkSHhod1lIN0xsc2VTSFRiUmcK4y0wpXjvwRfRbm4Adh4xikNgk+jwfpJo
            hY7yLYnCB8pzCUKxoP5j226crYi0RnssFV62gAfcnjM1uSQ4Aml1Ig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-24T12:21:44Z"
    mac: ENC[AES256_GCM,data:iBDnTg9hTQ5aDdJYUWWkxUNPLgz8OeZC1PpsifmrBPcMa8Ef0Oran2P+uj/BEu9dEEPL02x6JL8s2d470wgNW/FI7xDqCiA6XkR3xG0oa6xA61W3sIcVFv1sEcB3FaX6SzTf2PUhW316nF3oIWwLqi670Cq1b8qOE5iEX8GVANI=,iv:TlDOHvo7ijcQMVKKjJ9QT6gn/HMrgXr+9IErv1TCptM=,tag:pvsnBCN38aRYNU2r8CKMuw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
