---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: longhorn-secret
  namespace: storage
spec:
  target:
    deletionPolicy: Delete
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      type: Opaque
      data:
        AWS_ACCESS_KEY_ID: |-
          {{ .access_key }}
        AWS_SECRET_ACCESS_KEY: |-
          {{ .secret_key }}
        AWS_ENDPOINTS: |-
          {{ .endpoint }}
  data:
    - secretKey: access_key
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 5a98804c-6c54-4e09-817e-afd8012c70ad
        property: access_key
    - secretKey: secret_key
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 5a98804c-6c54-4e09-817e-afd8012c70ad
        property: secret_key
    - secretKey: endpoint
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 5a98804c-6c54-4e09-817e-afd8012c70ad
        property: endpoint
