apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:3KdDeiyQIbDn0Ym6vT4Vv2SJ8SlzqBLc5jWjxcaiySyIdICr,iv:3Smoyp2ukQQgg7qyB7MImh4n9OBSCtcb9gzg1+59gxY=,tag:tkFXGANTMamGOdn50sW9Mw==,type:str]
    credentials.json: ENC[AES256_GCM,data:tn7Y22GR6msTPQb8reeA7HalhgzpFnoV8NkovjmuCnjvb+T6iXzRRhezh0Jhyww69nIiuNzj1z0KJYxSfACSyJFTfeW0ji9PsuX2k2TVTmpG5NEpsbYMG7DFYKLw2fsMChMoedrhD+0xb2rQC9UA0ArZo65mllAC4KyFKb9cXRoYkxhIiQiJnEqMRdQ8x/AEoy9qVxKToiPQ6lscxSBQOkBzPx/w78VHa7Xik45iog==,iv:/2Skl8nMJOAyzlTylJpsogpBnJmXaVct2k9sLE6g3NQ=,tag:M4f6llbb5XBErCmbNLh8EQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1twdqg4pwl3ncan7rq2ynlhnjqaggj9cdwdw7cun4rzdj56mtq4nsvk674s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIWGQ0NC9QNHgydmdsQVFu
            MVArUHQ5ZWJ4UjJxUFg5RlNjOWF5bGc3dFFNCldZenNCZVpDYk9PSnVDa2hRMGcz
            VUZERlhjSE5NUzR6cWk2RzFyMWtIOUkKLS0tIHVmUkhOMjh1d2sxb0FYWHNtR0sx
            azlZWmVqS0hsbEdGMExNTXNUelhLSjAKK6Fizs/Jke6U6gfwqeCKIxRGU5PpRv2c
            rXM5b0YGP+k7IwSCW9BHHWq2Q5xLrjTWCNiM45SqSciuA8dKw/5EVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-04T14:57:37Z"
    mac: ENC[AES256_GCM,data:4mvOML/umM1q9jrZK9yakztz9pkcK0i0ohtGdyZVVRBPO7zSzc9re4b2Q2oNky2uge8hDifyX4KlD9LrhZQNbtUPVe5gGXEM5cbxkrPFlSW+zzO7qPR3OD6Nul9jBY7000SLJnu8Q0qs3yjyQXOqsA2EJYhWdea2YP0TcwnOixc=,iv:tHnKb17jKEyUK1rAqsfhIHU6f/xkbm5dmCDJ9tZ1/Q0=,tag:vCJTCRJg3RBcYyiJ0E5scA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
