apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:AGu0EQovCHzaJouL7LDBiJSU3TH+MYWIeVf/tEjXWuYGzsFi,iv:gA2X/yIIsetFBDSEhYW5wA6fsLBtE/PR1twMGOvvlO0=,tag:bRE9gz/bIRddAqmDUQuc/w==,type:str]
    credentials.json: ENC[AES256_GCM,data:7fLaFWE64qtxGOKHcQ92tx/tySCPkL1zynLb9zQRI7GKRXdhwXCpVcYS/Aqmab28JhvCLIhdDfHFx2JYaHJuQz0/+Wglw0MZsM7PNmrjfMtZZ/kSAIFgLTZbWUDBBL76Et9RvZNwa/OpNB9s8vUk9Fomi4ipNhabPpP71FNRQ3W+nveD379xLez9Cdiz8bGKHBxrVhZxWY7ATrlBergdr9L9BNkpSztIxhzDYhh/1g==,iv:NED2A6hfHgXIZyjRBOfuZhHZQmIMuJxgW8a2SYB3JsA=,tag:drNokrYMWzYVj5xOJkm/KA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1twdqg4pwl3ncan7rq2ynlhnjqaggj9cdwdw7cun4rzdj56mtq4nsvk674s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1UzdrTEhUUTNVSFBSY2RC
            dUsrYlJjZDNjaDgxLy8zWVpLczl2dWx6Y2hvCjV2dlB2dENKRzBUSHRoWGd3Kzcr
            cGJnTElCZEkvT3ZjVXBrVDdzTURHS0EKLS0tIDFOYkQrN2RMWVV5RzZETW5kcU5C
            ZkFvN1BJNXlBTlJNY2l5M1ZNbmxxSVEKsYOyb/qcguZpEfLSo40gq+qFSD+obz2w
            MUAoSY9MgLbO+tsgtRKIN14hhkm/g66eyIOmKIkptQq/OrN2nTB2nA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-24T12:21:30Z"
    mac: ENC[AES256_GCM,data:1AtMS1pgL19rPXUSHgpNDwrQrBSjsUz75i7N1IVPD0aWMC+npC84Aey0BB2TS3GW2SZaXTAM+BLioanxT7CKplNOvEcxv+Pxp7cqmOu9HN40TOaCrjt+RZBoz1gYn0pr2v8NQSIaNuz2AGBZFEBubnQHE1ZKoXcwOi6ykfl8O84=,iv:8KSSodOQqM1bmY+Rw2wzr1n2HLCzvEVncNrKBcMREdI=,tag:2EKOBJFTySd9JM+hrWU/zA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
